### ISSUE TITLE
Can you provide the code to generate "*. csv" files?

### ISSUE THREAD

**Issue by FriedaSmith** [Jason-Qiu/EEG_Language_Alignment#1]
Hello, how are the ***. csv** files generated below? Can you provide the code to generate them? In addition, when running the code on the **K-EmoCon** dataset, I found that the accuracy of the validation set was only 6%, while the training and testing sets were very high. What is the reason for this?

```
read = pd.read_csv('labels.csv')
sentiment = pd.read_csv('label.csv')
label = pd.read_csv('label_SA.csv', header = None)
```

**Comment by Chenpuh** [comment]
@FriedaSmith Did you find any solution to this?

**Comment by willxxy** [comment]
Hello @Chenpuh @FriedaSmith, I apologize for the late reply. I will try to reproduce the code and get back to you as soon as possible. In regards to the *.csv files, we did not include them in the repo due to size. I will reorganize the required files and link a google drive. Thank you for your patience.

**Comment by Chenpuh** [comment]
@willxxy Thank you for your reply. We look forward to your early reproduction of the code.

**Comment by willxxy** [comment]
Hello @Chenpuh @FriedaSmith, we have created the preprocessed sentence level csv file. It can be found at this [link](https://drive.google.com/drive/folders/13-cBoIc_fGIjx4WE8gOVW6jHTjCHM_mK?usp=sharing).

**Comment by FriedaSmith** [comment]
Thank you very much for your contribution.
